const CREATE_CANDIDATE = 'CREATE_CANDIDATE';
const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE';
const DELETE_CANDIDATE = 'DELETE_CANDIDATE';

export { CREATE_CANDIDATE, UPDATE_CANDIDATE, DELETE_CANDIDATE };
